import puppeteer from 'puppeteer-core'
const CHROME='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
const b=await puppeteer.launch({executablePath:CHROME,headless:'new',args:['--no-sandbox','--force-device-scale-factor=2'],defaultViewport:{width:1280,height:1600,deviceScaleFactor:2}})
const p=await b.newPage()
await p.goto('http://localhost:4173/',{waitUntil:'networkidle0'})
await p.evaluate(()=>localStorage.clear())
await p.reload({waitUntil:'networkidle0'})
await new Promise(r=>setTimeout(r,1200))
await p.screenshot({path:'/tmp/tv_dyn/cand1.png',fullPage:true})
await new Promise(r=>setTimeout(r,1800))
await p.screenshot({path:'/tmp/tv_dyn/cand2.png',fullPage:true})
await p.evaluate(()=>{window.scrollBy(0,200)})
await new Promise(r=>setTimeout(r,600))
await p.screenshot({path:'/tmp/tv_dyn/cand3.png',fullPage:true})
await b.close();console.log('OK')
